version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: user-auth-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: user_auth_db
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data

volumes:
  postgres_data_v2:
